name: 'Extract docker dns name'
description: 'Currently only supports Traefik labels (in docker-compose.prod.yml or docker-compose.yml)'
outputs:
  dns-name: 
    description: "The hostname as extracted"
    value: ${{ steps.extract.outputs.dns-name }}
runs:
  using: "composite"
  steps: 
    - id: extract
      name: Extract dns name from docker-compose.yml
      shell: bash
      run: |
        echo -n '::set-output name=dns-name::'
        # check the docker-compose.prod.yml file for a Host name first
        (grep "=Host(" docker-compose.prod.yml && sed -n 's/.*Host(\`\(.*\)\`.*/\1/p' < docker-compose.prod.yml) \
        # fall back to docker-compose.yml
        || sed -n 's/.*Host(\`\(.*\)\`.*/\1/p' < docker-compose.yml
