name: Tests

on: [push]

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - id: test-no-prod
      name: test/no-prod
      uses: ./
      with:
        workdir: ./test/no-prod/
    - run: |
        [ "${{ steps.test-no-prod.outputs.dns-name }}" == 'foo.bar.com' ]

    - id: test-prod
      name: test/prod
      uses: ./
      with:
        workdir: ./test/prod/
    - run: |
        [ '${{ steps.test-prod.outputs.dns-name }}' == 'foo.bar.com' ]